---
title: "Delimitation_manuscript"
author: "Lara Wootton"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chapter 2 introduction

The definition of a species has been a controversial topic in biodiversity science, largely because there is no single criterion that satisfactorily defines a species across all living organisms [@Mayden1997; @Queiroz1998; @Queiroz2005]. De Queiroz (2007) realised that the dissonance between species definitions was due to the speciation process itself. As a lineage bifurcates, it accumulates differences in morphology, genetic composition, ecology and degree of reproductive isolation. However, depending on the taxon, the order in which these features appear can vary, with some features occasionally not arising at all. This creates a grey zone in the speciation process, in which it can be ambiguous as to whether or not incipient species have effectively differentiated [@Queiroz1998]. While most contemporary species concepts accept that a species is an independently evolving lineage [@Queiroz2007], determining when speciation has occurred during the gradual divergence of two lineages can often be difficult. 

It has become clear that the heterogeneity in the speciation process renders the use of single criteria to delimit species insufficient [@Wiley1978; @Frost1995; @Queiroz2005; @Padial2008]. Therefore, a new holistic paradigm of taxonomy, termed integrative taxonomy [@Dayrat2005; @Padial2010], has been proposed to inform more robust species delimitation. Integrative taxonomy emphasises that multiple lines of evidence, which can include genetic, morphological, phylogenetic and ecological information, should be examined before delimiting and describing a species [@Dayrat2005; @Padial2010]. Despite the extensive implementation of Dayrat's (2005) integrative taxonomic approach (@Dayrat2005 has been cited over 1400 times to date), and the application of similar integrative approaches by numerous others, morphology remains one of the most important criteria for species delimitation, especially for plant taxa [@Rouhan2014; @Treurnicht2017]. Cryptic plant species therefore present a challenge to delimit due to the absence of defining morphological features. Molecular barcoding was initially touted as a solution to circumscribe cryptic species, and was proven to be efficient in many cases, especially in animals [@Hebert2004]. However, species delimitation using barcoding has several issues, including taxonomic decisions made on arbitrary genetic differences, the inappropriate resolution of barcoding genes for certain taxa, and difficulties of linking new DNA sequences to existing type specimens [@Tautz2003; @Moritz2004; @DeSalle2005; @Goulding2015]. Furthermore, there are concerns that over-reliance on genetic data will lead to taxonomic inflation [@Isaacs2004; @Coates2018; @Tattersall2007; @Zachos2013], even though the use of genetic information has also led to a reduction of species number in some groups [@Burbrink2000; @Devey2008].

Several recent studies have, therefore, employed integrative taxonomic protocols for the delimitation of cryptic species, and these share several common features [@Barley2013; @Jorger2013; @Fiser2018; @Singhal2019; @Chaplin2019]. Firstly, all of these protocols acknowledge that extensive population sampling along the entirety of a species complex's range is needed to get a clear idea of genetic relationships, gene flow and geographic range limits [@Bernardo2011]. This prevents the inference of spurious splits between populations which, despite appearing genetically isolated, actually represent points along a continuum of genetic variation [@Mason2020]. Next, strong genetic differentiation needs to be demonstrated between putative cryptic species. This differentiation should be shown using data that incorporate independently evolving regions of the genome, to ensure that variation in gene histories from different loci is represented [@Fujita2012]. Commonly used ways of testing genetic differentiation include distance-based methods, where species are delimited only if intraspecific genetic variation is less than interspecific variation [@Puillandre2012], tree-based methods [e.g. @Zhang2018], and coalescent methods [@Leache2014]. Ideally, more than one of these approaches should be used to evaluate hypothesised species boundaries. Following genetic analysis, morphology should be re-examined for the purpose of identifying potentially diagnostic, although subtle, trait differences that corroborate the genetic findings [@Barley2013; @Chaplin2019]. Finally, if possible given the distribution of the species complex, reproductive isolation between taxa should ideally be demonstrated through the absence of gene flow between sympatric or parapatric populations [@Singhal2019].  

By reducing the reliance on morphology, integrative protocols provide a framework for reassessing the status of infraspecific taxa such as subspecies, especially those described before genetic data was widely available. Subspecies are typically defined as a collection of morphologically variant, and geographically distinct populations [@Mayr1982], a definition which makes their evolutionary status unclear, resulting in several interpretations [@Hamilton1992]. For example, subspecies can be conceptualised as having no evolutionary status, and can be understood merely as an attempt to describe clinal variation in a genetically coherent species [@Amadon1949; @Patten2002]. More commonly, subspecies are interpreted as incipient species [@Mallet2007], where the rank is considered a stage in the evolutionary divergence of a broader species [@Tattersall2007; @Hawlitschek2012].  A further possibility is that subspecies represent evolutionarily-distinct species which have not been recognised as such, on the basis of morphological indistinctness or insufficient data [@Manier2004]. By considering genetic data, in conjunction with other lines of evidence, an integrative taxonomic approach allows for discrimination between these alternative scenarios.  

The most recent infrageneric taxonomy of the Cape _Ehrharta_ is that of @GibbsRussell1987, who divided the genus into seven informal species groups. Most of these groups occur predominately in the arid, lower-elevation, renosterveld and succulent karoo vegetation regions of the GCFR. Within these lowlands groups, there is little taxonomic confusion as the species are clearly morphologically distinct, with characters that easily distinguish the species. Conversely, within two of the three higher-elevation, fynbos-restricted groups, Setacea and Ramosa, the species limits are less clear. The Setacea group consists of two species, _E. setacea_ and _E. rupestris_, the former comprising four subspecies (_disticha, setacea, uniflora_ and _scabra_), while the latter contains three (_rupestris, tricostata_ and _dodii_). As noted by @GibbsRussell1987, these species and subspecies are morphologically similar and difficult to distinguish. While the subspecies in both groups tend to have distinct ranges, many of them occur in sympatry in the Caledon area, where intermediates also occur. Species limits are even less clear within the Ramosa group, which contains two species, _E. ramosa_ with two subspecies (_aphylla_ and _ramosa_), and _E. rehmannii_ with three subspecies (_rehmannii, filiformis_ and _subspicata_). @GibbsRussell1989 observe that "the five taxa comprising the Ramosa group intergrade and few consistently reliable characters adequately separate the species and subspecies". As these taxa were delimited using only morphological and anatomical characters, it is possible that the application of genetic data may bring clarity to species boundaries in this group. 

The archipelagic character of the Cape high-elevation zone lends itself to non-ecological vicariant or peripatric speciation, with the consequence that this zone potentially harbours many undiscovered cryptic species [@Britton2014; @Verboom2015]. The high- and mid-elevation Setacea and Ramosa groups of _Ehrharta_ are strong candidates for cryptic speciation, since their distributions encompass multiple mountain ranges between which the presence of deep valleys may restrict gene flow. Moreover, they contain multiple taxonomic entities which, by virtue of their weak morphological differentiation and relatively distinct geographical distribution, are currently conceptualised as subspecies, but may potentially represent distinct species. In this chapter, therefore, I employ an integrative taxonomic approach [@Dayrat2005] to test the hypothesis that subspecies within the mid- to high-elevation Ramosa and Setacea groups represent cryptic species that constitute distinct evolutionary lineages. In order to evaluate the monophyly of these groups and so provide context for their segregation into species, I first present a multilocus phylogenetic tree of the Cape _Ehrharta_ based on genome-wide targeted enrichment data [@Lemmon2012], with population-level sampling of the Setacea and Ramosa groups. In addition to insights obtained from these data, I employ the variation in single nucleotide polymorphisms (SNPs) generated through genotyping-by-sequencing [@Elshire2011], and in morphological traits to assess the evolutionary distinctiveness of putative species within these groups.